# Generated by Django 3.1.2 on 2020-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_key',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
