# Generated by Django 3.1.2 on 2020-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='policy_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
