# Generated by Django 3.1.2 on 2021-01-05 19:09

from django.db import migrations, models
import submission.insurancesubmission.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0002_auto_20201203_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='policy_document',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
    ]
