# Generated by Django 3.1.2 on 2021-03-06 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0003_insurancesubmission_policy_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
