# Generated by Django 3.1.2 on 2021-03-06 20:54

from django.db import migrations, models
import submission.insurancesubmission.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0004_insurancesubmission_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_submission_1',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_submission_2',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_submission_3',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_submission_4',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_submission_5',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_template_1',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_template_2',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_template_3',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_template_4',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='document_template_5',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
    ]
