# Generated by Django 3.1.2 on 2021-04-15 20:12

from django.db import migrations, models
import django.db.models.deletion
import submission.insurancesubmission.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0006_insurancesubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_submission_1',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_submission_2',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_submission_3',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_submission_4',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_submission_5',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_template_1',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_template_2',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_template_3',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_template_4',
        ),
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='document_template_5',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path)),
                ('document', models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path)),
                ('signature', models.ImageField(blank=True, default=None, upload_to='')),
                ('insurance_submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurancesubmission.insurancesubmission')),
            ],
        ),
    ]
