# Generated by Django 3.1.2 on 2021-04-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0007_auto_20210415_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='insurance_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurancesubmission.insurancesubmission'),
        ),
    ]
