# Generated by Django 3.1.2 on 2021-04-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0011_auto_20210428_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttoken',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurancesubmission.document'),
        ),
    ]
