# Generated by Django 3.1.2 on 2021-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0012_auto_20210428_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
