# Generated by Django 3.1.2 on 2021-05-10 15:42

from django.db import migrations, models
import submission.insurancesubmission.models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0014_document_page_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=submission.insurancesubmission.models.create_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='signature',
            field=models.ImageField(blank=True, default=None, upload_to=submission.insurancesubmission.models.create_path),
        ),
    ]
