# Generated by Django 3.1.2 on 2021-05-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0015_auto_20210510_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancesubmission',
            name='pdf',
        ),
    ]
