# Generated by Django 3.1.2 on 2021-06-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0016_remove_insurancesubmission_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesubmission',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
