# Generated by Django 3.1.2 on 2021-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0017_auto_20210613_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='payment_document',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
