# Generated by Django 3.1.2 on 2021-07-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0018_document_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='bic_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='iban_ending',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
