# Generated by Django 3.1.2 on 2021-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0019_auto_20210714_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
