# Generated by Django 3.1.2 on 2021-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0020_auto_20210715_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='provider_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
