# Generated by Django 3.1.2 on 2021-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesubmission', '0021_insurancesubmission_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesubmission',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubmission',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
