# Generated by Django 3.1.2 on 2020-12-02 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submission.id.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to=submission.id.models.create_path)),
                ('verified', models.BooleanField(default=False)),
                ('latest', models.BooleanField(default=True)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Submission',
            },
        ),
    ]
