# Generated by Django 3.1.2 on 2020-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsubmission',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
