# Generated by Django 3.1.2 on 2021-02-26 09:41

from django.db import migrations, models
import submission.id.models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_idsubmission_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsubmission',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to=submission.id.models.create_path),
        ),
    ]
