# Generated by Django 3.1.2 on 2021-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_idtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtoken',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
