# Generated by Django 3.1.2 on 2021-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0005_idtoken_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtoken',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
