# Generated by Django 3.1.2 on 2021-04-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0007_auto_20210415_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
