# Generated by Django 3.1.2 on 2020-10-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utype',
            field=models.IntegerField(default=0, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=320, verbose_name='Email Address'),
        ),
    ]
