# Generated by Django 3.1.2 on 2020-12-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20201118_1319'),
        ('user', '0006_auto_20201125_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insurances',
            field=models.ManyToManyField(to='insurance.Insurance'),
        ),
    ]
