# Generated by Django 3.1.2 on 2020-12-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_insurances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='insurances',
        ),
    ]
