# Generated by Django 3.1.2 on 2020-12-09 02:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.create_path),
        ),
    ]
