# Generated by Django 3.1.2 on 2021-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
