# Generated by Django 3.1.2 on 2021-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_phone_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_1',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address_2',
            new_name='street_number',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
