# Generated by Django 3.1.2 on 2020-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damagereport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='status',
            field=models.CharField(default='w', max_length=1),
        ),
    ]
