# Generated by Django 3.1.2 on 2020-12-04 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('damagereport', '0002_damagereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
