# Generated by Django 3.1.2 on 2020-12-11 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('damagereport', '0003_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
