# Generated by Django 3.1.2 on 2021-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damagereport', '0004_damagereport_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
